### ISSUE TITLE
How to get all the files

### ISSUE THREAD

**Issue by donaldli2020** [ProdigyPNP/ProdigySource#1]

**Comment by afkvido** [comment]
It's actually very easy.

1. Go to [math.prodigygame.com](https://math.prodigygame.com) then log in
2. Press **F12**
3. Select **Application** out of the menu (Elements, Console, Sources, Network, Application)
4. Scroll down to **Frames**
5. Expand **top**
6. Expand **Scripts**
7. easy, there's prodigy's source code. keep in mind that this isn't possible with PHEx, as it blocks the defualt game.min.js

**Comment by donaldli2020** [comment]
Please also turn on discussions.

**Comment by donaldli2020** [comment]
> 7. easy, there's prodigy's source code. keep in mind that this isn't possible with PHEx, as it blocks the default game.min.js

So you copy the files manually???

**Comment by donaldli2020** [comment]
but how do you get every single file in the game?

**Comment by afkvido** [comment]
> Please also turn on discussions.

I invited you to @ProdigyPNP,

**Comment by afkvido** [comment]
> So you copy the files manually???

There's a **Download** option when inspecting the files

**Comment by afkvido** [comment]
> but how do you get every single file in the game?

just like that :)

**Comment by donaldli2020** [comment]
> > but how do you get every single file in the game?
> 
> just like that :)

tried it out but... it only has the files that are loaded, not everything

**Comment by afkvido** [comment]
oh. idk then

**Comment by afkvido** [comment]
i just realized that im fucking dumb for manually copying the files

https://github.com/PatheticMustan/ProdigySourceBot
this is superior
